In [1]:
from ucimlrepo import fetch_ucirepo
from implementations import bayes
from implementations import id3
from implementations import random_forest
import matplotlib.pyplot as plt
from collections import Counter
import numpy as np
from typing import Tuple
import pandas as pd
import time
import importlib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [4]:
X = np.genfromtxt("../data_processed/credit_score/percentiles/X.csv",
                   delimiter=",",
                   dtype=None,
                   encoding="utf-8",
                   names=None)
l = len(X[0])
xx = np.zeros([X.shape[0], l])
for i in range(X.shape[0]):
    for j in range(l):
        xx[i,j] = X[i][j]
X = xx
y = np.loadtxt("../data_processed/credit_score/percentiles/y.csv", dtype=float, delimiter=",")

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=123)
accuracies = []
time1 = time.time()

for _ in range(1):
    y_pred = []
    rfc = random_forest.RandomForestClassifier(classifiers_number=50)
    rfc.fit(x_train, y_train, tree_percentage=0.0)

    samples = len(y_test)
    correctly_predicted = 0
    for sample, gt in zip(x_test, y_test):
        prediction = rfc.predict(sample)
        y_pred.append(np.argmax(prediction))
        print(prediction, gt)
        if np.argmax(prediction) == gt:
            correctly_predicted += 1

    y_pred = np.array(y_pred)

    print(f"Accuracy: {(correctly_predicted / samples) * 100:.2f}%")
    print(f"Elapsed time: {time.time()-time1:.2f} s")
    accuracies.append((correctly_predicted / samples) * 100)
print(f"Mean accuracy: {np.mean(accuracies):.2f}%")

[0. 0. 1.] 1.0
[0. 0. 1.] 2.0
[0. 1. 0.] 1.0
[0. 0. 1.] 2.0
[0.44 0.   0.56] 1.0
[0. 1. 0.] 0.0
[1. 0. 0.] 0.0
[1. 0. 0.] 1.0
[0. 0. 1.] 2.0
[0.82 0.18 0.  ] 0.0
[0.96 0.04 0.  ] 1.0
[0.  0.2 0.8] 1.0
[1. 0. 0.] 0.0
[1. 0. 0.] 0.0
[0. 1. 0.] 1.0
[0. 0. 1.] 1.0
[0.68 0.32 0.  ] 1.0
[0. 1. 0.] 1.0
[0. 0. 1.] 1.0
[1. 0. 0.] 0.0
[0. 1. 0.] 1.0
[1. 0. 0.] 1.0
[1. 0. 0.] 0.0
[0. 0. 1.] 1.0
[0. 1. 0.] 0.0
[0. 1. 0.] 1.0
[0. 1. 0.] 1.0
[1. 0. 0.] 0.0
[0. 1. 0.] 1.0
[1. 0. 0.] 0.0
[0. 0. 1.] 2.0
[0. 1. 0.] 1.0
[0.   0.92 0.08] 1.0
[1. 0. 0.] 1.0
[0. 1. 0.] 1.0
[0. 0. 1.] 1.0
[0. 0. 1.] 1.0
[0. 1. 0.] 2.0
[0. 1. 0.] 1.0
[1. 0. 0.] 1.0
[1. 0. 0.] 0.0
[0. 0. 1.] 1.0
[0. 1. 0.] 0.0
[0. 1. 0.] 1.0
[0. 1. 0.] 1.0
[0. 1. 0.] 1.0
[0. 0. 1.] 2.0
[0. 1. 0.] 1.0
[1. 0. 0.] 0.0
[1. 0. 0.] 1.0
[0.   0.28 0.72] 1.0
[0. 1. 0.] 1.0
[1. 0. 0.] 0.0
[0. 0. 1.] 1.0
[0.   0.04 0.96] 1.0
[0. 1. 0.] 1.0
[0. 1. 0.] 1.0
[0. 0. 1.] 1.0
[1. 0. 0.] 1.0
[0. 0. 1.] 2.0
[0. 1. 0.] 2.0
[0. 1. 0.] 1.0
[0. 1. 0.] 1.0
[1. 0. 0.]

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=["abnormal", "normal", "inconclusive"])
disp.plot()
plt.show()